language: node_js
node_js:
  - "node"
env:
  - DBSTRING=mongodb://localhost:27017
before_install:
  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 2930ADAE8CAF5059EE73BB4B58712A2291FA4AD5
  - echo "deb [ arch=amd64 ] https://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.6 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.6.list
  - sudo apt-get update
  - sudo ln -s /usr/local/bin/node /usr/bin/node
  - sudo ln -s /usr/local/lib/node /usr/lib/node
  - sudo ln -s /usr/local/bin/npm /usr/bin/npm
  - sudo ln -s /usr/local/bin/node-waf /usr/bin/node-waf
  - ls /usr/bin/env
install:
  - sudo apt-get install -y mongodb-org
  - npm install
  - npm install -g nodemon
before_script:
  - sudo service mongod start
  - sleep 8s
  - cat /var/log/mongodb/mongod.log
  - node setup
  - sudo $(which nodemon) controller.js
  - sleep 8s
script:
  - npm test