language: node_js
node_js:
  - "node"
before_install:
  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 2930ADAE8CAF5059EE73BB4B58712A2291FA4AD5
  - echo "deb [ arch=amd64 ] https://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.6 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.6.list
  - sudo apt-get update
install:
  - sudo apt-get install -y mongodb-org
  - npm install
  - npm install pm2 -g
before_script:
  - sudo service mongod start
  - sleep 8s
  - cat /var/log/mongodb/mongod.log
  - node setup
  - pm2 start controller.js
script:
  - npm test