# Set language to node
language: node_js
# Set node version to latest
node_js:
  - "node"
# Set localhost db as environment db string to simulate creation
env:
  - DBSTRING=mongodb://localhost:27017
before_install:
  # prereqs for mongo
  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 2930ADAE8CAF5059EE73BB4B58712A2291FA4AD5
  - echo "deb [ arch=amd64 ] https://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.6 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.6.list
  - sudo apt-get update
install:
  # install mongo
  - sudo apt-get install -y mongodb-org
  # install everything and runner
  - npm install
  - npm install --save-dev nodemon
before_script:
  - sudo service mongod start
  - sleep 8s
  - cat /var/log/mongodb/mongod.log
  - node setup
  - sudo $(which npm) run start-travis
  - sleep 8s
script:
  - sudo $(which npm) test